disabled_rules: # rule identifiers to exclude from running
#  - colon
#  - comma
#  - control_statement
#  - file_length
#  - force_cast
  - force_try
#  - function_body_length
#  - leading_whitespace
#  - line_length
#  - nesting
#  - operator_whitespace
#  - opening_brace
#  - return_arrow_whitespace
#  - statement_position
#  - todo
#  - trailing_newline
#  - trailing_semicolon
  - trailing_whitespace
#  - type_body_length
#  - type_name
  - valid_docs
# - variable_name
  - variable_name_min_length
#  - variable_name_max_length
opt_in_rules: # some rules are only opt-in
  - force_unwrapping
  - generic_type_name
  - implicit_getter
  - implicit_return
  - implicitly_unwrapped_optional
  - large_tuple
  - operator_whitespace
  - operator_usage_whitespace
  - return_arrow_whitespace
  - syntactic_sugar
  - vertical_parameter_alignment_on_call
  - vertical_parameter_alignment
  - vertical_whitespace
# Find all the available rules by running:
# swiftlint rules
excluded: # paths to ignore during linting. overridden by `included`.
  - Carthage
  - Pods
  - fastlane
  - XLProjectName/Helpers/R-Swift/R.generated.swift
# parameterized rules can be customized from this configuration file
file_length:
  - 700
  - 1000
line_length:
  - 230
  - 250
# parameterized rules are first parameterized as a warning level, then error level.
function_body_length:
  - 150 # warning
  - 200 # error
type_body_length:
  - 300 # warning
  - 400 # error
variable_name_max_length:
  - 30 # warning
  - 40 # error
variable_name_min_length:
  - 2 # warning
  - 1 # error
